name: rustful


services:
  postgres:
    image: postgres:latest
    container_name: ${DATABASE}
    restart: unless-stopped
    secrets:
      - postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fakes}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      start_period: 5s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rusty_network

  migration:
    build:
      context: .
      target: migration
    container_name: ${MIGRATION_CONTAINER_NAME}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rusty_network

  backend:
    build:
      context: .
      target: final
    container_name: ${BACKEND_CONTAINER_NAME}
    restart: always
    ports:
      - 5001:5001
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    networks:
      - rusty_network


networks:
    rusty_network:
      driver: bridge


volumes:
  postgres-data:


secrets:
  postgres_password:
    file: db/pass.txt
