name: CI

on:
  push:
    branches: [main]
  pull_reruest:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: inspect
        run: |
          ls -al
          whoami
          pwd
          node -v
