name: CI
on:
  pull_request:
    branches:
      - main
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  pr-format:
    runs-on: ubuntu-latest

    steps:
      - name: 'PR format check'
        uses: 'androidx/check-pr-format-action@main'
        with:
          checks: '["(.*)?JIRA(.*)?"]'
            # '["(https:\/\/optimizely.atlassian.net\/browse\/){1}(DATA|DSSM){1}-{1}([0-9]+)"]'

  audit:
    needs: pr-format
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: inspect
        run: |
          ls -al
          whoami
          pwd
          node -v
