name: CI
on: [push]
jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: inspect
        run: |
          ls -al
          whoami
          pwd
          node -v
